var profiles = {
            "Hoover's" : {
                            'name' : "Hoover\'s",
                            'logo' : 'hoovers-logo.png',
                            'bio'   : "Hoover Alexander’s  roots run deep through Texas. A native East Austinite and a fifth-generation Texan, Hoover and his cooking are inspired by the state itself. Hoover has always associated food with bringing people together, and the delicious and distinct flavors on our menu strive to bring together the melting pot of cultures and people who make up this great state.",
                            'phone' : "(512) 479-5006",
                            'website': "www.hooverscooking.com",
                            'address': "2002 Manor Rd, Austin, TX 78722",
                            'gradient' : "radial-gradient(50% 150%, #FDC92B   50%, #FB9813   100%)",
                            'fonts' : ['Open Sans','Oswald'],
                            'colors' : ['#FFE001','#C83C09','#F88C00','#009ADD','#B6561B','#FFFFFF'],
                            'photos' : [ { "photoType" : "customer",
                                           "photoFile" : [ "hoovers-1.jpg",
                                                           "hoovers-2.jpg",
                                                           "hoovers-3.jpg",
                                                           "hoovers-4.jpg",
                                                           "hoovers-5.jpg",
                                                           "hoovers-6.jpg" ] },
                                         { "photoType" : "ugc",
                                           "photoFile" : [ "hoovers-25.jpg",
                                                           "hoovers-26.jpg",
                                                           "hoovers-27.jpg",
                                                           "hoovers-28.jpg",
                                                           "hoovers-29.jpg",
                                                           "hoovers-30.jpg",
                                                           "hoovers-31.jpg",
                                                           "hoovers-32.jpg",
                                                           "hoovers-33.jpg" ] },
                                         { "photoType" : "freelance",
                                           "photoFile" : [ "hoovers-7.jpg",
                                                           "hoovers-8.jpg",
                                                           "hoovers-9.jpg",
                                                           "hoovers-10.jpg",
                                                           "hoovers-11.jpg",
                                                           "hoovers-12.jpg",
                                                           "hoovers-13.jpg",
                                                           "hoovers-14.jpg",
                                                           "hoovers-15.jpg",
                                                           "hoovers-16.jpg",
                                                           "hoovers-17.jpg",
                                                           "hoovers-18.jpg",
                                                           "hoovers-19.jpg",
                                                           "hoovers-20.jpg",
                                                           "hoovers-21.jpg" ] },
                                         { "photoType" : "testimonial",
                                           "photoFile" : [ "hoovers-22.jpg",
                                                           "hoovers-23.jpg",
                                                           "hoovers-24.jpg" ] } ]

                          },

            "Eagle Transmission" : {
                            'name' : "Eagle Transmission",
                            'logo' : 'eagle-logo.png',
                            'bio'   : "Our goal is to deliver to each customer the transmission repair, service or, if needed, a completely rebuilt transmission at a fair price. Transmissions are our specialty and in fact transmission & driveline repairs are all we do.",
                            'phone' : "(512) 448-4747",
                            'website': "www.austineagletransmission.com",
                            'address': "6218 Manchaca Rd, Austin, TX 78745",
                            'gradient' : "radial-gradient(50% 150%, #EC4747  50%, #D9242A  100%)",
                            'fonts' : ['Helvetica Neue','PT Sans Narrow'],
                            'colors' : ['#D9242A','#173785','#304050','#DEE7F1'],
                            'photos' : [ { "photoType" : "freelance",
                                           "photoFile" : [ "eagle-1.jpg",
                                                           "eagle-2.jpg",
                                                           "eagle-3.jpg",
                                                           "eagle-4.jpg" ] } ]
                          },

            "Elements" : {
                            'name' : 'Elements',
                            'logo' : 'elements-logo.png',
                            'bio'   : "Elements Laser Spa is the leading laser hair removal clinic in Austin. Elements has been voted Best of Citysearch for the past four years. Come experience award winning laser hair removal at Elements Laser Spa in Austin.",
                            'phone' : "(512) 992-0517",
                            'website': "www.elementslaserspa.com",
                            'address': "3801 S Congress Ave #106, Austin, TX 78704",
                            'gradient' : "radial-gradient(50% 150%, #B3F4F6  50%, #1BB5CA  100%)",
                            'fonts' : ['Playfair Display','Tahoma'],
                            'colors' : ['#B3F4F6','#1BB5CA','#76899E','#F2EFEC','#D1C5B7','#DF3B39'],
                            'photos' : [
                                         { "photoType" : "freelance",
                                           "photoFile" : [ "elements-1.jpg",
                                                           "elements-2.jpg",
                                                           "elements-3.jpg",
                                                           "elements-4.jpg" ] } ]
                          },
}
