var profiles = {
            "Delish" : {
                            'name' : "Delish",
                            'logo' : 'logo-delish.png',
                            'bio'   : "Delish began in 2009, the fulfillment of a lifelong dream of founder Lisa Matulis-Thomajan. Over the years, Delish has grown from a tiny cupcake shop offering a few flavors to a full service cake and dessert bakery. Our scratch made delectables are hand crafted and served by our passionate, creative, and experienced staff members.",
                            'phone' : "(512) 473-4118",
                            'website': "www.delishaustin.com/",
                            'address': "209 W. 3rd Street, Austin, Texas 78701",
                            'fonts' : ['Damion','Lato'],
                            'colors' : ['#FFE800','#E6CA80','#5E5132','#FF738E','#FF002F','#14FCFC','#1D2024','#A8EA5A','#FFF'],
                            'photos' : ['https://drive.google.com/uc?id=0B_TWeTee0fCmY3JNektqbVluYkU',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmb1FMZk1xSnkzMm8',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmU242NWhzR29XejA',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmRDVzaERnVDJJMDg',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmVTRTM21HZG9KVjA',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmLVkwY3h1QVo3cVU',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmYXo3VENnMGdEQjg',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmbzNLSl9DRnd5aDg',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmcHdsaFN2VEUxRGM',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmb0wyMlZ1dnU5ZVk',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmdWotLUhIWG9aOGc']
                          },
            "Hoover's" : {
                            'name' : "Hoover\'s",
                            'logo' : 'logo-hoovers.png',
                            'bio'   : "Hoover Alexander’s  roots run deep through Texas. A native East Austinite and a fifth-generation Texan, Hoover and his cooking are inspired by the state itself. Hoover has always associated food with bringing people together, and the delicious and distinct flavors on our menu strive to bring together the melting pot of cultures and people who make up this great state.",
                            'phone' : "(512) 479-5006",
                            'website': "www.hooverscooking.com",
                            'address': "2002 Manor Rd, Austin, TX 78722",
                            'fonts' : ['Open Sans','Oswald'],
                            'colors' : ['#FFE001','#C83C09','#F88C00','#009ADD','#B6561B','#FFFFFF'],
                            'photos' : ['https://drive.google.com/uc?id=0B_TWeTee0fCmR05EenhLQVRqcFU',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmdy15UVpFRHluWlk',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmWld0dnhGdDJhRk0',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmYVNxTU85NFJOdmM',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmTHkybTZDUEMxbGc']
                          },

            "Eagle Transmission" : {
                            'name' : "Eagle Transmission",
                            'logo' : 'logo-eagletransmission.png',
                            'bio'   : "Our goal is to deliver to each customer the transmission repair, service or, if needed, a completely rebuilt transmission at a fair price. Transmissions are our specialty and in fact transmission & driveline repairs are all we do.",
                            'phone' : "(512) 448-4747",
                            'website': "www.austineagletransmission.com",
                            'address': "6218 Manchaca Rd, Austin, TX 78745",
                            'fonts' : ['League Spartan','League Gothic','PT Sans Narrow'],
                            'colors' : ['#D9242A','#173785','#304050','#DEE7F1','#FFF'],
                            'photos' : ['https://drive.google.com/uc?id=0B_TWeTee0fCmS2J3WHE4ZzFEdGc',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmbEg2ZkJNdWl3ODQ',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmdFFidnFUelZSbkU',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmendyYmVxMFBySFk']
                          },

            "Elements" : {
                            'name' : 'Elements',
                            'logo' : 'logo-elements.png',
                            'bio'   : "Elements Laser Spa is the leading laser hair removal clinic in Austin. Elements has been voted Best of Citysearch for the past four years. Come experience award winning laser hair removal at Elements Laser Spa in Austin.",
                            'phone' : "(512) 992-0517",
                            'website': "www.elementslaserspa.com",
                            'address': "3801 S Congress Ave #106, Austin, TX 78704",
                            'fonts' : ['Playfair Display','Tahoma'],
                            'colors' : ['#B3F4F6','#1BB5CA','#76899E','#F2EFEC','#D1C5B7','#DF3B39','#FFF'],
                            'photos' : ['https://drive.google.com/uc?id=0B_TWeTee0fCmY0Qtc1p5cFdadVU',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmc19TRjFTUlFSdG8',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmbVZrQ2xYRGNNOVE',
                                        'https://drive.google.com/uc?id=0B_TWeTee0fCmRm9VQ1NMWlhhS1E']
                          },
}
